spring.application.name=firstapp
info.app.name = 'Ritika'




#custom properties

coach.name = udemy
coach.course = a to z ds


server.port = 4200
server.servlet.context-path  = /myFirstApp


#set lazy intialization (it will make whole applicationlazy  , no instance is created until  required)
#spring.main.lazy-initialization= true