spring.application.name=firstapp
info.app.name = 'Ritika'




#custom properties

coach.name = udemy
coach.course = a to z ds


server.port = 4200
server.servlet.context-path  = /myFirstApp


#set lazy intialization (it will make whole applicationlazy  , no instance is created until  required)
#spring.main.lazy-initialization= true


#setting database properties

spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=ritika

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#off spring boot banner
spring.main.banner-mode = off


#set logging level to warn
logging.level.root = warn